version: "3"

services:
  web:
    build: .
    container_name: expense-control-rails
    ports: ["3000:3000"]
    tty: true
    stdin_open: true
    volumes:
      - .:/expense_control/
    expose: ["3000"]
    environment:
      - PG_HOST=db
      - PG_USERNAME=postgres
      - PG_PASSWORD=postgres
    links:
      - db
#    mem_limit: 1024m

  db:
    image: postgres:10.5
    container_name: expense-control-db
    environment:
      POSTGRES_DB: expense_control_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports: ["5432:5432"]
    expose: ["5432"]
  #   mem_limit: 64m
  #  mem_reservation: 100m



